# Generated by Django 2.1.7 on 2019-03-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('AB_Gurtschloss_BF', models.DecimalField(decimal_places=2, max_digits=20)),
                ('AB_Gurtschloss_FA', models.DecimalField(decimal_places=2, max_digits=20)),
                ('AB_Gurtschloss_Reihe2_BF', models.DecimalField(decimal_places=2, max_digits=20)),
                ('AB_Gurtschloss_Reihe2_FA', models.DecimalField(decimal_places=2, max_digits=20)),
                ('AB_Gurtschloss_Reihe2_MI', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BCM1_Aussen_Temp_ungef', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BH_Blinker_li', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BH_Blinker_re', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BH_Fernlicht', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BH_Lichthupe', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_Bremsdruck', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_Fahrer_bremst', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_Gierrate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_HL_Fahrtrichtung', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_HL_Radgeschw_02', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_HR_Fahrtrichtung', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_HR_Radgeschw_02', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_Laengsbeschl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_Querbeschleunigung', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_VL_Fahrtrichtung', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_VL_Radgeschw_02', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_VR_Fahrtrichtung', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_VR_Radgeschw_02', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_VZ_Gierrate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ESP_v_Signal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('FS_Luftfeuchte_rel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('FS_Temp_Sensor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('KBI_Aussen_Temp_gef', models.DecimalField(decimal_places=2, max_digits=20)),
                ('KBI_Kilometerstand_2', models.DecimalField(decimal_places=2, max_digits=20)),
                ('KBI_Tankfuellstand_Prozent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LV_Abblendlicht_Anzeige', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LV_Fernlicht_Anzeige', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LV_Nebellicht_Anzeige', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LV_Nebelschlusslicht_Anzeige', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LV_Standlicht_Anzeige', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LV_Tagfahrlicht_Anzeige', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LWI_Lenkradw_Geschw', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LWI_Lenkradwinkel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LWI_VZ_Lenkradw_Geschw', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LWI_VZ_Lenkradwinkel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MO_Drehzahl_01', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MO_Fahrpedalrohwert_01', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MO_Gangposition', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MO_Kuppl_schalter', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ND_Heading', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ND_UTC', models.DecimalField(decimal_places=2, max_digits=20)),
                ('NP_Altitude', models.DecimalField(decimal_places=2, max_digits=20)),
                ('NP_Fix', models.DecimalField(decimal_places=2, max_digits=20)),
                ('NP_LatDegree', models.DecimalField(decimal_places=2, max_digits=20)),
                ('NP_LongDegree', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Wischer_vorne_aktiv', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
